import { Product, Translation, Customer, Supplier, Category } from './types';

export const TRANSLATIONS: Translation = {
  searchPlaceholder: { en: 'Search product, SKU, or scan...', ar: 'بحث عن منتج، رمز، أو مسح...' },
  total: { en: 'Total', ar: 'المجموع' },
  subtotal: { en: 'Subtotal', ar: 'المجموع الفرعي' },
  discount: { en: 'Discount', ar: 'خصم' },
  pay: { en: 'Pay', ar: 'دفع' },
  park: { en: 'Park', ar: 'تعليق' },
  parkedOrders: { en: 'Parked Orders', ar: 'طلبات معلقة' },
  settings: { en: 'Settings', ar: 'الإعدادات' },
  addToCart: { en: 'Add', ar: 'إضافة' },
  variants: { en: 'Options', ar: 'خيارات' },
  cancel: { en: 'Cancel', ar: 'إلغاء' },
  confirm: { en: 'Confirm', ar: 'تأكيد' },
  clearCart: { en: 'Clear', ar: 'مسح' },
  refundMode: { en: 'Refund Mode', ar: 'وضع الاسترجاع' },
  offline: { en: 'Offline Mode', ar: 'وضع عدم الاتصال' },
  online: { en: 'Online', ar: 'متصل' },
  emptyCart: { en: 'Cart is empty', ar: 'السلة فارغة' },
  qty: { en: 'Qty', ar: 'كمية' },
  item: { en: 'Item', ar: 'صنف' },
  price: { en: 'Price', ar: 'السعر' },
  holdSuccess: { en: 'Order Parked Successfully', ar: 'تم تعليق الطلب بنجاح' },
  checkoutSuccess: { en: 'Transaction Completed', ar: 'تمت العملية بنجاح' },
  noParkedOrders: { en: 'No parked orders', ar: 'لا يوجد طلبات معلقة' },
  inventory: { en: 'Inventory', ar: 'المخزون' },
  pos: { en: 'Point of Sale', ar: 'نقطة البيع' },
  stock: { en: 'Stock', ar: 'المخزون' },
  cost: { en: 'Cost', ar: 'التكلفة' },
  margin: { en: 'Margin', ar: 'الربح' },
  lowStock: { en: 'Low Stock', ar: 'مخزون منخفض' },
  update: { en: 'Update', ar: 'تحديث' },
  actions: { en: 'Actions', ar: 'إجراءات' },
  adjustStock: { en: 'Adjust', ar: 'تعديل' },
  saveChanges: { en: 'Save Changes', ar: 'حفظ التغييرات' },
  payment: { en: 'Payment', ar: 'الدفع' },
  addDiscount: { en: 'Add Discount', ar: 'إضافة خصم' },
  tip: { en: 'Tip', ar: 'بقشيش' },
  splitPayment: { en: 'Split Payment', ar: 'تقسيم الدفع' },
  remaining: { en: 'Remaining', ar: 'المتبقي' },
  cash: { en: 'Cash', ar: 'نقدي' },
  card: { en: 'Card', ar: 'بطاقة' },
  gift: { en: 'Gift Card', ar: 'بطاقة هدية' },
  wallet: { en: 'Wallet', ar: 'محفظة' },
  check: { en: 'Check', ar: 'شيك' },
  apply: { en: 'Apply', ar: 'تطبيق' },
  customAmount: { en: 'Custom Amount', ar: 'مبلغ مخصص' },
  finalize: { en: 'Finalize', ar: 'إنهاء' },
  emailReceipt: { en: 'Email Receipt', ar: 'إيصال بالبريد' },
  printReceipt: { en: 'Print Receipt', ar: 'طباعة الإيصال' },
  itemDiscount: { en: 'Item Discount', ar: 'خصم الصنف' },
  remove: { en: 'Remove', ar: 'إزالة' },
  hardware: { en: 'Hardware', ar: 'الأجهزة' },
  autoPrint: { en: 'Auto-Print Receipt', ar: 'طباعة تلقائية' },
  kickDrawer: { en: 'Kick Cash Drawer', ar: 'فتح درج النقود' },
  customerDisplay: { en: 'Customer Display', ar: 'شاشة العميل' },
  openDisplay: { en: 'Open Display', ar: 'فتح الشاشة' },
  printerWidth: { en: 'Printer Width', ar: 'عرض الطابعة' },
  testPrint: { en: 'Test Print', ar: 'طباعة تجريبية' },
  soundEffects: { en: 'Sound Effects', ar: 'مؤثرات صوتية' },
  welcome: { en: 'Welcome', ar: 'مرحباً بكم' },
  items: { en: 'items', ar: 'أصناف' },
  scanBarcode: { en: 'Scan Barcode', ar: 'مسح الباركود' },
  // Reports
  reports: { en: 'Reports', ar: 'التقارير' },
  dashboard: { en: 'Dashboard', ar: 'لوحة التحكم' },
  totalSales: { en: 'Total Sales', ar: 'إجمالي المبيعات' },
  transactions: { en: 'Transactions', ar: 'المعاملات' },
  avgBasket: { en: 'Avg. Basket', ar: 'متوسط السلة' },
  topProducts: { en: 'Top Products', ar: 'أفضل المنتجات' },
  byCategory: { en: 'Sales by Category', ar: 'المبيعات حسب الفئة' },
  byPayment: { en: 'Sales by Payment', ar: 'المبيعات حسب الدفع' },
  inventoryValue: { en: 'Inventory Value', ar: 'قيمة المخزون' },
  potentialRevenue: { en: 'Potential Revenue', ar: 'الإيرادات المحتملة' },
  lowStockItems: { en: 'Low Stock Items', ar: 'عناصر منخفضة المخزون' },
  exportCsv: { en: 'Export CSV', ar: 'تصدير CSV' },
  noData: { en: 'No data available', ar: 'لا توجد بيانات' },
  // Inventory Management
  addProduct: { en: 'Add Product', ar: 'إضافة منتج' },
  editProduct: { en: 'Edit Product', ar: 'تعديل منتج' },
  deleteProduct: { en: 'Delete Product', ar: 'حذف منتج' },
  confirmDelete: { en: 'Are you sure you want to delete this product?', ar: 'هل أنت متأكد من حذف هذا المنتج؟' },
  nameEn: { en: 'Name (EN)', ar: 'الاسم (EN)' },
  nameAr: { en: 'Name (AR)', ar: 'الاسم (AR)' },
  sku: { en: 'SKU', ar: 'SKU' },
  barcode: { en: 'Barcode', ar: 'الباركود' },
  category: { en: 'Category', ar: 'الفئة' },
  minStock: { en: 'Min Stock', ar: 'الحد الأدنى' },
  color: { en: 'Color', ar: 'اللون' },
  save: { en: 'Save', ar: 'حفظ' },
  suppliers: { en: 'Suppliers', ar: 'الموردين' },
  categories: { en: 'Categories', ar: 'الفئات' },
  history: { en: 'History', ar: 'السجل' },
  addSupplier: { en: 'Add Supplier', ar: 'إضافة مورد' },
  editSupplier: { en: 'Edit Supplier', ar: 'تعديل مورد' },
  addCategory: { en: 'Add Category', ar: 'إضافة فئة' },
  contact: { en: 'Contact', ar: 'اتصال' },
  address: { en: 'Address', ar: 'العنوان' },
  movement: { en: 'Movement', ar: 'حركة' },
  received: { en: 'Received', ar: 'استلام' },
  adjustment: { en: 'Adjustment', ar: 'تعديل' },
  return: { en: 'Return', ar: 'إرجاع' },
  sale: { en: 'Sale', ar: 'بيع' },
  products: { en: 'Products', ar: 'المنتجات' },
  // Shift Management
  shiftManagement: { en: 'Shift Management', ar: 'إدارة الوردية' },
  openShift: { en: 'Open Shift', ar: 'فتح الوردية' },
  closeShift: { en: 'Close Shift', ar: 'إغلاق الوردية' },
  startFloat: { en: 'Starting Float', ar: 'رصيد البداية' },
  expectedCash: { en: 'Expected Cash', ar: 'النقد المتوقع' },
  actualCash: { en: 'Actual Cash', ar: 'النقد الفعلي' },
  variance: { en: 'Variance', ar: 'الفروقات' },
  safeDrop: { en: 'Safe Drop', ar: 'سحب للخزنة' },
  payout: { en: 'Pay Out', ar: 'مصروفات' },
  shiftClosed: { en: 'Shift Closed', ar: 'الوردية مغلقة' },
  shiftClosedMsg: { en: 'You must open a shift to process transactions.', ar: 'يجب فتح وردية لإجراء المعاملات.' },
  reason: { en: 'Reason', ar: 'السبب' },
  amount: { en: 'Amount', ar: 'المبلغ' },
  zReport: { en: 'Z-Report', ar: 'تقرير الإغلاق (Z)' },
  // Kitchen & Order Type (Removed)
  customer: { en: 'Customer', ar: 'عميل' },
  note: { en: 'Note', ar: 'ملاحظة' },
  // CRM
  crm: { en: 'Customers', ar: 'العملاء' },
  phone: { en: 'Phone', ar: 'الهاتف' },
  email: { en: 'Email', ar: 'البريد' },
  points: { en: 'Points', ar: 'نقاط' },
  visits: { en: 'Visits', ar: 'زيارات' },
  lastVisit: { en: 'Last Visit', ar: 'آخر زيارة' },
  addCustomer: { en: 'Add Customer', ar: 'إضافة عميل' },
  editCustomer: { en: 'Edit Customer', ar: 'تعديل عميل' },
  redeemPoints: { en: 'Redeem Points', ar: 'استبدال النقاط' },
  loyaltyDiscount: { en: 'Loyalty Reward', ar: 'مكافأة ولاء' },
  guest: { en: 'Walk-in Customer', ar: 'عميل زائر' },
  selectCustomer: { en: 'Select Customer', ar: 'اختر عميل' },
  searchCustomer: { en: 'Search Name or Phone', ar: 'بحث بالاسم أو الهاتف' },
};

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat1', name: 'Beverages', nameAr: 'مشروبات' },
  { id: 'cat2', name: 'Food', nameAr: 'طعام' },
  { id: 'cat3', name: 'Dessert', nameAr: 'حلويات' },
  { id: 'cat4', name: 'Retail', nameAr: 'تجزئة' },
];

export const MOCK_SUPPLIERS: Supplier[] = [
  { id: 'sup1', name: 'Bean Co.', contactName: 'Jim Bean', phone: '555-1234', email: 'jim@beanco.com', address: '123 Coffee Ln' },
  { id: 'sup2', name: 'Bakery Supplies', contactName: 'Sarah Flour', phone: '555-5678', email: 'sarah@bakery.com' },
];

export const MOCK_PRODUCTS: Product[] = [
  { id: '1', name: 'Espresso', nameAr: 'إسبريسو', sku: 'BV-001', price: 3.50, costPrice: 0.50, stock: 150, minStock: 20, category: 'Beverages', categoryId: 'cat1', color: '#a1887f' },
  { 
    id: '2', 
    name: 'Latte', 
    nameAr: 'لاتيه', 
    sku: 'BV-002', 
    price: 4.50, 
    costPrice: 0.80,
    stock: 85,
    minStock: 20,
    category: 'Beverages', 
    categoryId: 'cat1',
    color: '#d7ccc8',
    variants: [
      { id: 'v1', name: 'Oat Milk', priceModifier: 0.5 },
      { id: 'v2', name: 'Vanilla', priceModifier: 0.5 },
      { id: 'v3', name: 'Extra Shot', priceModifier: 1.0 },
    ]
  },
  { id: '3', name: 'Cappuccino', nameAr: 'كابتشينو', sku: 'BV-003', price: 4.00, costPrice: 0.75, stock: 90, minStock: 15, category: 'Beverages', categoryId: 'cat1', color: '#8d6e63' },
  { id: '4', name: 'Green Tea', nameAr: 'شاي أخضر', sku: 'BV-004', price: 3.00, costPrice: 0.20, stock: 45, minStock: 10, category: 'Beverages', categoryId: 'cat1', color: '#a5d6a7' },
  { id: '5', name: 'Croissant', nameAr: 'كرواسون', sku: 'FD-001', price: 3.75, costPrice: 1.20, stock: 12, minStock: 15, category: 'Food', categoryId: 'cat2', color: '#ffcc80', supplierId: 'sup2' },
  { id: '6', name: 'Bagel', nameAr: 'بيجل', sku: 'FD-002', price: 2.50, costPrice: 0.50, stock: 8, minStock: 10, category: 'Food', categoryId: 'cat2', color: '#ffe0b2', supplierId: 'sup2' },
  { id: '7', name: 'Muffin', nameAr: 'مافن', sku: 'FD-003', price: 3.25, costPrice: 0.90, stock: 24, minStock: 10, category: 'Food', categoryId: 'cat2', color: '#ffb74d', supplierId: 'sup2' },
  { id: '8', name: 'Sandwich', nameAr: 'ساندويتش', sku: 'FD-004', price: 8.50, costPrice: 3.50, stock: 5, minStock: 10, category: 'Food', categoryId: 'cat2', color: '#ffab91' },
  { id: '9', name: 'Salad', nameAr: 'سلطة', sku: 'FD-005', price: 9.00, costPrice: 4.00, stock: 7, minStock: 5, category: 'Food', categoryId: 'cat2', color: '#c8e6c9' },
  { id: '10', name: 'Cookie', nameAr: 'كوكيز', sku: 'FD-006', price: 2.00, costPrice: 0.40, stock: 45, minStock: 20, category: 'Dessert', categoryId: 'cat3', color: '#d7ccc8', supplierId: 'sup2' },
  { id: '11', name: 'Water', nameAr: 'ماء', sku: 'BV-005', price: 1.50, costPrice: 0.10, stock: 200, minStock: 50, category: 'Beverages', categoryId: 'cat1', color: '#80deea' },
  { id: '12', name: 'Juice', nameAr: 'عصير', sku: 'BV-006', price: 4.00, costPrice: 1.50, stock: 30, minStock: 10, category: 'Beverages', categoryId: 'cat1', color: '#ffcc80' },
];

export const MOCK_CUSTOMERS: Customer[] = [
  { id: 'c1', name: 'Alice Walker', phone: '555-0101', email: 'alice@example.com', points: 120, totalSpent: 150.50, visitCount: 5, lastVisit: Date.now() - 86400000, joinedAt: Date.now() - 100000000 },
  { id: 'c2', name: 'Bob Jones', phone: '555-0102', points: 45, totalSpent: 45.00, visitCount: 2, lastVisit: Date.now() - 172800000, joinedAt: Date.now() - 50000000 },
  { id: 'c3', name: 'Charlie Day', phone: '555-0103', email: 'charlie@example.com', points: 350, totalSpent: 410.25, visitCount: 12, lastVisit: Date.now() - 3600000, joinedAt: Date.now() - 200000000 },
];